"""Add trial_expires_at to User

Revision ID: d43e2691b629
Revises: 46f5c8d1b315
Create Date: 2026-03-27 13:48:21.392543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'd43e2691b629'
down_revision: Union[str, None] = '46f5c8d1b315'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_events_campaign_id'))
        batch_op.drop_index(batch_op.f('ix_email_events_message_id'))
        batch_op.drop_index(batch_op.f('ix_email_events_prospect_id'))

    op.drop_table('email_events')
    with op.batch_alter_table('spam_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_spam_reports_created_at'))
        batch_op.drop_index(batch_op.f('ix_spam_reports_status'))
        batch_op.drop_index(batch_op.f('ix_spam_reports_user_id'))

    op.drop_table('spam_reports')
    op.drop_table('workspace_members')
    with op.batch_alter_table('niche_burn_benchmarks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_niche_burn_benchmarks_date'))
        batch_op.drop_index(batch_op.f('ix_niche_burn_benchmarks_niche'))

    op.drop_table('niche_burn_benchmarks')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_audit_events_user_id'))

    op.drop_table('audit_events')
    op.drop_table('job_diffs')
    with op.batch_alter_table('webhook_endpoints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webhook_endpoints_user_id'))

    op.drop_table('webhook_endpoints')
    with op.batch_alter_table('campaign_steps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaign_steps_campaign_id'))

    op.drop_table('campaign_steps')
    with op.batch_alter_table('campaign_prospects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaign_prospects_campaign_id'))
        batch_op.drop_index(batch_op.f('ix_campaign_prospects_email'))

    op.drop_table('campaign_prospects')
    with op.batch_alter_table('suppressed_emails', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suppressed_emails_user_hash'))

    op.drop_table('suppressed_emails')
    op.drop_table('workspaces')
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaigns_workspace_id'))

    op.drop_table('campaigns')
    with op.batch_alter_table('smtp_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_smtp_accounts_workspace_id'))

    op.drop_table('smtp_accounts')
    with op.batch_alter_table('tracked_domains', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tracked_domains_user_id'))

    op.drop_table('tracked_domains')
    with op.batch_alter_table('list_aging_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_list_aging_snapshots_job_id'))

    op.drop_table('list_aging_snapshots')
    with op.batch_alter_table('domain_health_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_domain_health_logs_domain_id'))

    op.drop_table('domain_health_logs')
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)

    with op.batch_alter_table('billing_events', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('bounce_events', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)

    with op.batch_alter_table('burn_pool', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)
        batch_op.alter_column('job_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)

    with op.batch_alter_table('export_presets', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)

    with op.batch_alter_table('job_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spam_copy_flagged', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('spam_copy_reason', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('is_blacklisted', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('blacklist_reason', sa.String(), nullable=True))
        batch_op.alter_column('job_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)

    with op.batch_alter_table('marketplace_fees', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('trade_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)

    with op.batch_alter_table('marketplace_listings', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)

    with op.batch_alter_table('marketplace_trades', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('listing_a_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)
        batch_op.alter_column('listing_b_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trial_expires_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.alter_column('registration_ip',
               existing_type=sa.TEXT(),
               type_=sa.String(length=45),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('registration_ip',
               existing_type=sa.String(length=45),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.drop_column('trial_expires_at')

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('marketplace_trades', schema=None) as batch_op:
        batch_op.alter_column('listing_b_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('listing_a_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('marketplace_listings', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('marketplace_fees', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('trade_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('job_results', schema=None) as batch_op:
        batch_op.alter_column('job_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.drop_column('blacklist_reason')
        batch_op.drop_column('is_blacklisted')
        batch_op.drop_column('spam_copy_reason')
        batch_op.drop_column('spam_copy_flagged')

    with op.batch_alter_table('export_presets', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('burn_pool', schema=None) as batch_op:
        batch_op.alter_column('job_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)

    with op.batch_alter_table('bounce_events', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)

    with op.batch_alter_table('billing_events', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    op.create_table('domain_health_logs',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('domain_id', sa.CHAR(length=32), nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), nullable=False),
    sa.Column('blacklisted_on', sqlite.JSON(), nullable=True),
    sa.Column('checked_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['domain_id'], ['tracked_domains.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('domain_health_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_domain_health_logs_domain_id'), ['domain_id'], unique=False)

    op.create_table('list_aging_snapshots',
    sa.Column('id', sa.NUMERIC(), nullable=False),
    sa.Column('job_id', sa.NUMERIC(), nullable=False),
    sa.Column('user_id', sa.NUMERIC(), nullable=False),
    sa.Column('day_number', sa.INTEGER(), nullable=False),
    sa.Column('fresh_count', sa.INTEGER(), nullable=True),
    sa.Column('warm_count', sa.INTEGER(), nullable=True),
    sa.Column('burned_count', sa.INTEGER(), nullable=True),
    sa.Column('torched_count', sa.INTEGER(), nullable=True),
    sa.Column('avg_burn_score', sa.FLOAT(), nullable=True),
    sa.Column('total_emails', sa.INTEGER(), nullable=True),
    sa.Column('freshness_pct', sa.FLOAT(), nullable=True),
    sa.Column('captured_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('list_aging_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_list_aging_snapshots_job_id'), ['job_id'], unique=False)

    op.create_table('tracked_domains',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('user_id', sa.CHAR(length=32), nullable=False),
    sa.Column('domain_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), nullable=True),
    sa.Column('last_checked_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tracked_domains', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tracked_domains_user_id'), ['user_id'], unique=False)

    op.create_table('smtp_accounts',
    sa.Column('id', sa.NUMERIC(), nullable=False),
    sa.Column('workspace_id', sa.NUMERIC(), nullable=False),
    sa.Column('label', sa.VARCHAR(length=100), nullable=False),
    sa.Column('provider', sa.VARCHAR(length=50), nullable=False),
    sa.Column('from_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('from_email', sa.VARCHAR(length=255), nullable=False),
    sa.Column('smtp_host', sa.VARCHAR(length=255), nullable=False),
    sa.Column('smtp_port', sa.INTEGER(), nullable=False),
    sa.Column('smtp_user', sa.VARCHAR(length=255), nullable=False),
    sa.Column('smtp_pass_encrypted', sa.VARCHAR(length=500), nullable=False),
    sa.Column('imap_host', sa.VARCHAR(length=255), nullable=True),
    sa.Column('imap_port', sa.INTEGER(), nullable=True),
    sa.Column('daily_limit', sa.INTEGER(), nullable=False),
    sa.Column('warmup_enabled', sa.BOOLEAN(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('smtp_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_smtp_accounts_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('campaigns',
    sa.Column('id', sa.NUMERIC(), nullable=False),
    sa.Column('workspace_id', sa.NUMERIC(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaigns_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('workspaces',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('owner_id', sa.CHAR(length=32), nullable=False),
    sa.Column('plan', sa.VARCHAR(length=50), nullable=True),
    sa.Column('credits_remaining', sa.INTEGER(), nullable=True),
    sa.Column('brand_company_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('brand_color', sa.VARCHAR(length=20), nullable=True),
    sa.Column('brand_logo_url', sa.VARCHAR(length=1024), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('suppressed_emails',
    sa.Column('id', sa.NUMERIC(), nullable=False),
    sa.Column('user_id', sa.NUMERIC(), nullable=False),
    sa.Column('email_hash', sa.VARCHAR(length=64), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('suppressed_emails', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_suppressed_emails_user_hash'), ['user_id', 'email_hash'], unique=1)

    op.create_table('campaign_prospects',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('campaign_id', sa.CHAR(length=32), nullable=False),
    sa.Column('job_result_id', sa.CHAR(length=32), nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), nullable=False),
    sa.Column('variables', sqlite.JSON(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), nullable=False),
    sa.Column('current_step_number', sa.INTEGER(), nullable=False),
    sa.Column('next_send_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_result_id'], ['job_results.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campaign_prospects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaign_prospects_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaign_prospects_campaign_id'), ['campaign_id'], unique=False)

    op.create_table('campaign_steps',
    sa.Column('id', sa.NUMERIC(), nullable=False),
    sa.Column('campaign_id', sa.NUMERIC(), nullable=False),
    sa.Column('step_number', sa.INTEGER(), nullable=False),
    sa.Column('wait_days', sa.INTEGER(), nullable=False),
    sa.Column('subject_template', sa.VARCHAR(length=500), nullable=False),
    sa.Column('body_template', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campaign_steps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaign_steps_campaign_id'), ['campaign_id'], unique=False)

    op.create_table('webhook_endpoints',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('user_id', sa.CHAR(length=32), nullable=False),
    sa.Column('url', sa.VARCHAR(length=500), nullable=False),
    sa.Column('secret_key', sa.VARCHAR(length=100), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('webhook_endpoints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webhook_endpoints_user_id'), ['user_id'], unique=False)

    op.create_table('job_diffs',
    sa.Column('id', sa.NUMERIC(), nullable=False),
    sa.Column('user_id', sa.NUMERIC(), nullable=False),
    sa.Column('job_a_id', sa.NUMERIC(), nullable=False),
    sa.Column('job_b_id', sa.NUMERIC(), nullable=False),
    sa.Column('summary', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['job_a_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_b_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_events',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('workspace_id', sa.CHAR(length=32), nullable=True),
    sa.Column('user_id', sa.CHAR(length=32), nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('resource_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('resource_id', sa.VARCHAR(length=100), nullable=True),
    sa.Column('metadata_json', sqlite.JSON(), nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_created_at'), ['created_at'], unique=False)

    op.create_table('niche_burn_benchmarks',
    sa.Column('id', sa.NUMERIC(), nullable=False),
    sa.Column('niche', sa.VARCHAR(length=100), nullable=False),
    sa.Column('date', sa.DATETIME(), nullable=False),
    sa.Column('avg_fresh_pct', sa.FLOAT(), nullable=True),
    sa.Column('avg_warm_pct', sa.FLOAT(), nullable=True),
    sa.Column('avg_burned_pct', sa.FLOAT(), nullable=True),
    sa.Column('avg_torched_pct', sa.FLOAT(), nullable=True),
    sa.Column('avg_burn_score', sa.FLOAT(), nullable=True),
    sa.Column('total_jobs_sampled', sa.INTEGER(), nullable=True),
    sa.Column('total_emails_sampled', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('niche_burn_benchmarks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_niche_burn_benchmarks_niche'), ['niche'], unique=False)
        batch_op.create_index(batch_op.f('ix_niche_burn_benchmarks_date'), ['date'], unique=False)

    op.create_table('workspace_members',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('workspace_id', sa.CHAR(length=32), nullable=False),
    sa.Column('user_id', sa.CHAR(length=32), nullable=False),
    sa.Column('role', sa.VARCHAR(length=50), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spam_reports',
    sa.Column('id', sa.NUMERIC(), nullable=False),
    sa.Column('user_id', sa.NUMERIC(), nullable=False),
    sa.Column('job_id', sa.NUMERIC(), nullable=True),
    sa.Column('raw_emails', sa.TEXT(), nullable=False),
    sa.Column('reason', sa.VARCHAR(length=100), nullable=False),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('reviewed_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('spam_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_spam_reports_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_spam_reports_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_spam_reports_created_at'), ['created_at'], unique=False)

    op.create_table('email_events',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('campaign_id', sa.CHAR(length=32), nullable=False),
    sa.Column('prospect_id', sa.CHAR(length=32), nullable=False),
    sa.Column('smtp_account_id', sa.CHAR(length=32), nullable=True),
    sa.Column('message_id', sa.VARCHAR(length=255), nullable=True),
    sa.Column('event_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('metadata_', sqlite.JSON(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prospect_id'], ['campaign_prospects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['smtp_account_id'], ['smtp_accounts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_events_prospect_id'), ['prospect_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_events_message_id'), ['message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_events_campaign_id'), ['campaign_id'], unique=False)

    # ### end Alembic commands ###
